export const Vizeler = [
  {
    ders: "matematik",
    soru: "1.soruankara nerde",
    cevapA: "marmara",
    cevapB: "iç anadolu",
    cevapC: "güney",
    cevapD: "mars",
    cevapE: "kars",
    cevap: "B",
    //en kötü tüm soruları iç içe koyarak kullanırım altına ders adı ve türü eklerim
  },
  {
    ders: "matematik",
    soru: "2.soru1+1",
    cevapA: "13",
    cevapB: "2",
    cevapC: "1",
    cevapD: "4",
    cevapE: "kars",
    cevap: "B",
  },
  {
    ders: "matematik",
    soru: "3.soru2+2",
    cevapA: "13",
    cevapB: "2",
    cevapC: "1",
    cevapD: "4",
    cevapE: "kars",
    cevap: "D",
  },
  {
    ders: "matematik",
    soru: "kars",
    cevapA: "13",
    cevapB: "2",
    cevapC: "1",
    cevapD: "4",
    cevapE: "kars",
    cevap: "E",
  },
];
