export const Vizeler = [
  {
    ders: "Matematik",
    soru: "√9 Kaçtır ?",
    cevapA: "-3",
    cevapB: "81",
    cevapC: "27",
    cevapD: "3",
    cevapE: "9",
    cevap: "D",
  },
  {
    ders: "Matematik",
    soru: "÷ Hangi işlemi ifade eder ?",
    cevapA: "Toplama",
    cevapB: "Çıkarma",
    cevapC: "Bölme",
    cevapD: "Çarpma",
    cevapE: "Kök Alma",
    cevap: "C",
  },
  {
    ders: "Matematik",
    soru: "Dairenin çevresi nasıl hesaplanır ?",
    cevapA: "2.π.r",
    cevapB: "π.r²",
    cevapC: "π+r²",
    cevapD: "π.r².(α/360)",
    cevapE: "π²",
    cevap: "A",
  },
];
